### ISSUE TITLE
 raise KeyError(key) from None KeyError: 'DJANGO_SECRET_KEY'

### ISSUE THREAD

**Issue by d0nat3ll0** [jimhoekstra/ping-pong-pals#1]
raise KeyError(key) from None
KeyError: 'DJANGO_SECRET_KEY'

Do you know how to fix this I'm new sorry

**Comment by jimhoekstra** [comment]
Hi! I'm sorry that this is not documented yet. Before running the application you need to set the 'DJANGO_SECRET_KEY' environment variable. This is used to set the SECRET_KEY setting in Django.

You can set an environment variable in your terminal by:
 - In Linux, by running: export DJANGO_SECRET_KEY=abc
 - In Windows, by running: set DJANGO_SECRET_KEY=abc

**Comment by jimhoekstra** [comment]
I implemented a change such that when environment variables are not set, safe default values are chosen and the application will run successfully.
